# Generated by Django 3.0.13 on 2021-05-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
    ]
