# Generated by Django 3.0.13 on 2021-05-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
    ]
