# Generated by Django 3.0.13 on 2021-05-03 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0002_auto_20210409_0025"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.TextField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
