# Generated by Django 3.0.13 on 2021-05-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0003_auto_20210503_1800"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
